class CraftRound extends BaseRound {
  constructor(key,meta,done,order){ super(key,meta,done); this.order=order; this.chosen={color:null,decos:[],container:null}; this.mixed=false; this.mixAngle=0; this.mixStart=0; this.lastAngle=null; }
  create(){ super.create(); this.customer=this.circleFace(1040,280,.76); this.slime=this.add.ellipse(650,420,230,125,0xb8a1ff,1).setStrokeStyle(4,COLORS.ink,.15).setInteractive({useHandCursor:true}); this.slime.baseScale={x:1,y:1}; this.decorateText=this.add.text(650,555,'색을 고르고, 섞고, 장식한 뒤 SERVE!',{fontFamily:'Arial',fontSize:'17px',fontStyle:'bold',color:'#607086'}).setOrigin(.5);
    this.orderBubble=this.add.container(1030,500).setScale(.7);const bg=this.add.graphics();bg.fillStyle(0xffffff,1).fillRoundedRect(-135,-70,270,140,24);bg.lineStyle(3,COLORS.ink,.15).strokeRoundedRect(-135,-70,270,140,24);this.orderBubble.add(bg);this.orderLabel=this.add.text(0,-38,'ORDER',{fontFamily:'Arial',fontSize:'14px',fontStyle:'bold',color:'#607086'}).setOrigin(.5);this.orderIcons=this.add.text(0,8,this.orderText(),{fontSize:'26px',align:'center'}).setOrigin(.5);this.orderBubble.add([this.orderLabel,this.orderIcons]);this.tweens.add({targets:this.orderBubble,scale:1,duration:220,ease:'Back.Out',delay:450});
    this.makeColorButtons(); this.makeDecos(); if(this.order.container)this.makeContainers(); this.makeMixRing(); this.makeServe(); this.hintTarget={x:260,y:250};
    this.slime.on('pointerdown',p=>{if(!this.mixed)return;this.stretchStart={x:p.x,y:p.y};audio.pickup();});this.input.on('pointermove',p=>{if(!p.isDown||!this.stretchStart||!this.mixed)return;const dx=p.x-this.stretchStart.x,dy=p.y-this.stretchStart.y;this.slime.setScale(Phaser.Math.Clamp(1+Math.abs(dx)/420,1,FEEL.slime.stretchMax),Phaser.Math.Clamp(1-Math.abs(dy)/650,FEEL.slime.squashMin,1.15));});this.input.on('pointerup',()=>{if(this.stretchStart){this.stretchStart=null;this.tweens.add({targets:this.slime,scaleX:1,scaleY:1,duration:FEEL.slime.releaseDuration,ease:'Elastic.Out'});}});
  }
  orderText(){ const color={blue:'🔵',green:'🟢',pink:'🩷'}[this.order.color]; const deco={star:'⭐',flower:'🌼',heart:'💗'}[this.order.deco]; const jar=this.order.container?'  🫙':''; return `${color}  ${deco}${jar}`; }
  makeColorButtons(){[['blue',COLORS.blue],['green',COLORS.green],['pink',0xff8fab]].forEach(([k,c],i)=>{const x=220+i*115;const b=this.add.circle(x,250,36,c,1).setStrokeStyle(4,COLORS.ink,.15).setInteractive({useHandCursor:true});b.on('pointerup',()=>{this.chosen.color=k;this.tweens.add({targets:b,scale:1.2,yoyo:true,duration:120});this.tweens.addCounter({from:0,to:100,duration:300,onUpdate:tw=>{const p=tw.getValue()/100;const cc=Phaser.Display.Color.Interpolate.ColorWithColor(Phaser.Display.Color.ValueToColor(this.slime.fillColor),Phaser.Display.Color.ValueToColor(c),100,p*100);this.slime.setFillStyle(Phaser.Display.Color.GetColor(cc.r,cc.g,cc.b),1);}});audio.plop();});});this.add.text(330,190,'색상',{fontFamily:'Arial',fontSize:'15px',fontStyle:'bold',color:'#607086'}).setOrigin(.5);}
  makeDecos(){ const arr=[['star','⭐'],['flower','🌼'],['heart','💗'],['banana','🍌']];arr.forEach(([k,e],i)=>{const c=this.add.text(210+i*95,360,e,{fontSize:'38px',backgroundColor:'#ffffff',padding:{left:10,right:10,top:8,bottom:8}}).setOrigin(.5).setInteractive({useHandCursor:true});this.input.setDraggable(c);c.home={x:c.x,y:c.y};c.on('drag',(p,x,y)=>{c.x=x;c.y=y;});c.on('dragend',()=>{if(Phaser.Math.Distance.Between(c.x,c.y,650,420)<145){this.chosen.decos.push(k);this.snap(c,610+this.chosen.decos.length*32,390+(this.chosen.decos.length%2)*45,()=>audio.pop());}else this.wrongReturn(c);});});this.add.text(350,315,'장식',{fontFamily:'Arial',fontSize:'15px',fontStyle:'bold',color:'#607086'}).setOrigin(.5);}
  makeContainers(){ [['round','◯'],['square','▢']].forEach(([k,e],i)=>{const c=this.makeLabel(230+i*150,500,e+' 용기',120,k==='round'?COLORS.sky:COLORS.gray).setInteractive(new Phaser.Geom.Rectangle(-60,-28,120,56),Phaser.Geom.Rectangle.Contains);c.on('pointerup',()=>{this.chosen.container=k;this.tweens.add({targets:c,scale:1.08,yoyo:true,duration:130});audio.pickup();});}); }
  makeMixRing(){ this.ring=this.add.circle(650,420,155,0xffffff,.02).setStrokeStyle(4,0x5aa9e6,.25).setInteractive(new Phaser.Geom.Circle(0,0,170),Phaser.Geom.Circle.Contains);this.ring.on('pointerdown',p=>{this.mixStart=this.time.now;this.lastAngle=Phaser.Math.RadToDeg(Math.atan2(p.y-420,p.x-650));});this.ring.on('pointermove',p=>{if(!p.isDown)return;const a=Phaser.Math.RadToDeg(Math.atan2(p.y-420,p.x-650));if(this.lastAngle!==null){this.mixAngle+=Math.abs(Phaser.Math.Angle.ShortestBetween(this.lastAngle,a));this.slime.setRotation(this.slime.rotation+.04);if(this.mixAngle>=FEEL.slime.mixAngle&&this.time.now-this.mixStart>=FEEL.slime.minMixTime&&!this.mixed){this.mixed=true;this.sparkle(650,420,12);audio.success();this.decorateText.setText('잘 섞였어요! 늘려보고 장식한 뒤 SERVE!');}this.lastAngle=a;}}); }
  makeServe(){ const b=this.add.text(650,635,'SERVE',{fontFamily:'Arial',fontSize:'20px',fontStyle:'bold',color:'#ffffff',backgroundColor:'#ff7f6a',padding:{left:28,right:28,top:12,bottom:12}}).setOrigin(.5).setInteractive({useHandCursor:true});b.on('pointerup',()=>this.serve(b)); }
  serve(b){ const colorOk=this.chosen.color===this.order.color, decoOk=this.chosen.decos.includes(this.order.deco), containerOk=!this.order.container||this.chosen.container===this.order.container, mixOk=this.mixed; if(colorOk&&decoOk&&containerOk&&mixOk){b.disableInteractive();this.happy(this.customer);this.sparkle(1040,280,12);audio.coin();const coins=this.meta.round===1?3:this.meta.round===2?5:8;for(let i=0;i<coins;i++){const c=this.add.text(650,420,'●',{fontSize:'22px',color:'#ffb703'}).setOrigin(.5);this.tweens.add({targets:c,x:920+(i%4)*28,y:350-(i%2)*30,duration:480,delay:i*35,ease:'Cubic.Out',onComplete:()=>c.destroy()});}const creativity=Math.min(10,Math.max(0,this.chosen.decos.length-1)*5);this.time.delayedCall(900,()=>this.finish({score:90+creativity}));} else {this.curious(this.customer);this.orderIcons.setScale(1);this.tweens.add({targets:this.orderIcons,scale:1.14,yoyo:true,repeat:1,duration:140});this.decorateText.setText(!mixOk?'먼저 충분히 섞어볼까요?':'주문 아이콘을 다시 확인해보세요. 만든 것은 그대로 유지됩니다.');audio.boop();} }
}
