class CraftRound extends BaseRound {
  constructor(key,meta,done,order){super(key,meta,done);this.order=order;this.chosen={color:null,decos:[],container:null};this.ingredients=new Set();this.mixed=false;this.mixAngle=0;this.mixStart=0;this.lastAngle=null;this.slimeBlob=null;this.coinCount=0;}
  create(){
    super.create();this.face=this.customer=this.circleFace(1080,265,.74);this.customer.setX(1325);this.scheduleCharacterIdle();this.tweens.add({targets:this.customer,x:1080,duration:420,ease:'Cubic.Out'});
    this.bowl=this.makeBowl(650,420);this.base=this.makeBottle(230,230,0xf3f6fa,'BASE','base');this.activator=this.makeBottle(360,230,0x9bdff0,'ACT','activator');this.colors=this.makeColorButtons();this.decos=this.makeDecos();if(this.order.container)this.makeContainers();this.makeOrderBubble();this.makeMixSurface();this.makeServe();
    this.status=this.add.text(650,585,'BASE와 ACT를 그릇에 넣고 주문 색을 고른 뒤 섞어요',{fontFamily:'Arial',fontSize:'17px',fontStyle:'bold',color:'#607086'}).setOrigin(.5);this.hintTarget={x:this.base.x,y:this.base.y};
  }
  update(){this.slimeBlob?.update();}
  makeBowl(x,y){const c=this.add.container(x,y),g=this.add.graphics();g.fillStyle(0xeef4f8,1).fillEllipse(0,0,330,145);g.lineStyle(5,COLORS.ink,.15).strokeEllipse(0,0,330,145);g.fillStyle(0xcbdbe5,.55).fillEllipse(0,18,280,90);c.add(g);c.setSize(350,180);return c;}
  makeBottle(x,y,color,label,kind){const c=this.add.container(x,y).setName(kind),g=this.add.graphics();g.fillStyle(color,1).fillRoundedRect(-38,-55,76,110,18);g.fillStyle(COLORS.dark,.35).fillRoundedRect(-20,-70,40,20,7);c.add([g,this.add.text(0,15,label,{fontFamily:'Arial',fontSize:'13px',fontStyle:'bold',color:'#24314a'}).setOrigin(.5)]);c.setSize(100,150);c.width=100;c.height=150;c.kind=kind;this.dragify(c,{end:o=>this.dropIngredient(o)});return c;}
  dropIngredient(o){if(dist(o.x,o.y,650,420)>185){this.wrongReturn(o,'ingredient_drop',this.bowl);return;}if(this.ingredients.has(o.kind)){this.wrongReturn(o,'ingredient_repeat',this.bowl);return;}this.snap(o,540+(this.ingredients.size*65),365,()=>{this.ingredients.add(o.kind);audio.plop();this.squashBowl();this.time.delayedCall(260,()=>this.tweens.add({targets:o,x:o.home.x,y:o.home.y,duration:180}));if(this.ingredients.size===2){this.status.setText('주문과 같은 색을 골라 섞어볼까요?');this.hintTarget={x:this.order.color==='blue'?210:this.order.color==='green'?325:440,y:355};}});}
  squashBowl(){this.tweens.add({targets:this.bowl,scaleY:.94,scaleX:1.04,yoyo:true,duration:110,ease:'Sine.InOut'});}
  makeOrderBubble(){this.orderBubble=this.add.container(1070,500).setScale(.7);const bg=this.add.graphics();bg.fillStyle(0xffffff,1).fillRoundedRect(-145,-78,290,156,24);bg.lineStyle(3,COLORS.ink,.15).strokeRoundedRect(-145,-78,290,156,24);this.orderLabel=this.add.text(0,-43,'ORDER',{fontFamily:'Arial',fontSize:'14px',fontStyle:'bold',color:'#607086'}).setOrigin(.5);this.orderIcons=this.add.text(0,8,this.orderText(),{fontSize:'30px',align:'center'}).setOrigin(.5);this.orderBubble.add([bg,this.orderLabel,this.orderIcons]);this.tweens.add({targets:this.orderBubble,scale:1,duration:220,ease:'Back.Out',delay:450});}
  orderText(){const color={blue:'🔵',green:'🟢',pink:'🩷'}[this.order.color],deco={star:'★',flower:'✿',heart:'♥'}[this.order.deco],jar=this.order.container?'  ◯':'';return `${color}  ${deco}${jar}`;}
  makeColorButtons(){const arr=[['blue',COLORS.blue,210],['green',COLORS.green,325],['pink',0xff8fab,440]];arr.forEach(([k,c,x])=>{const b=this.add.circle(x,355,36,c,1).setStrokeStyle(4,COLORS.ink,.15).setInteractive({useHandCursor:true}).setName('color_'+k);b.on('pointerup',()=>this.pickColor(k,c,b));});this.add.text(325,300,'색상',{fontFamily:'Arial',fontSize:'15px',fontStyle:'bold',color:'#607086'}).setOrigin(.5);return arr;}
  pickColor(k,c,b){if(this.ingredients.size<2){this.curious(b);this.registerFailure('color_before_ingredients',this.bowl);return;}this.chosen.color=k;audio.plop();this.tweens.add({targets:b,scale:1.2,yoyo:true,duration:120});this.liquidColor=c;const fill=this.add.ellipse(650,430,255,80,c,.78).setDepth(5).setName('liquid');if(this.liquid&&this.liquid.active)this.liquid.destroy();this.liquid=fill;this.status.setText('그릇 안을 원을 그리며 충분히 섞어요');this.hintTarget={x:650,y:420};}
  makeMixSurface(){this.mixZone=this.add.zone(650,420,340,210).setInteractive(new Phaser.Geom.Ellipse(0,0,340,210),Phaser.Geom.Ellipse.Contains).setDepth(55);this.mixZone.on('pointerdown',p=>{if(!this.chosen.color||this.ingredients.size<2)return;this.mixStart=this.time.now;this.lastAngle=Phaser.Math.RadToDeg(Math.atan2(p.y-420,p.x-650));telemetry('mix_start');});this.mixZone.on('pointermove',p=>{if(!p.isDown||!this.chosen.color||this.ingredients.size<2||this.mixed)return;const a=Phaser.Math.RadToDeg(Math.atan2(p.y-420,p.x-650));if(this.lastAngle!==null){const d=Math.abs(Phaser.Math.Angle.ShortestBetween(this.lastAngle,a));this.mixAngle+=d;if(this.liquid)this.liquid.setRotation(this.liquid.rotation+d*.0022);if(Math.floor(this.mixAngle/120)!==Math.floor((this.mixAngle-d)/120))audio.scrub();if(this.mixAngle>=FEEL.slime.mixAngle&&this.time.now-this.mixStart>=FEEL.slime.minMixTime)this.completeMix();this.lastAngle=a;}});}
  completeMix(){if(this.mixed)return;this.mixed=true;if(this.liquid)this.liquid.destroy();this.bowl.setAlpha(.32);this.slimeBlob=new JellyBlob(this,650,420,this.liquidColor||COLORS.purple);this.sparkle(650,420,12);audio.success();this.status.setText('슬라임을 직접 늘려보고 주문 장식을 올려요');this.hintTarget={x:210,y:485};telemetry('mix_complete',{angle:Math.round(this.mixAngle),ms:Math.round(this.time.now-this.mixStart)});}
  makeDecos(){const arr=[['star','★'],['flower','✿'],['heart','♥'],['banana','◒']];arr.forEach(([k,e],i)=>{const c=this.add.container(210+i*95,485).setName('deco_'+k),g=this.add.graphics();g.fillStyle(0xffffff,1).fillCircle(0,0,38);g.lineStyle(2,COLORS.ink,.12).strokeCircle(0,0,38);const t=this.add.text(0,0,e,{fontFamily:'Arial',fontSize:'28px',fontStyle:'bold',color:k==='heart'?'#ff6b8a':'#6c63ff'}).setOrigin(.5);c.add([g,t]);c.setSize(82,82);c.width=82;c.height=82;c.kind=k;this.dragify(c,{end:o=>this.dropDeco(o)});});this.add.text(350,430,'장식',{fontFamily:'Arial',fontSize:'15px',fontStyle:'bold',color:'#607086'}).setOrigin(.5);}
  dropDeco(o){if(!this.mixed||!this.slimeBlob?.contains(o.x,o.y)){this.wrongReturn(o,'deco_drop',{x:650,y:420});return;}this.chosen.decos.push(o.kind);const idx=this.chosen.decos.length-1,x=615+(idx%4)*34,y=395+Math.floor(idx/4)*35;this.snap(o,x,y,()=>{o.disableInteractive();audio.pop();this.status.setText('원하면 더 만져보고, 준비되면 SERVE를 눌러요');});}
  makeContainers(){[['round','◯',230,COLORS.sky],['square','▢',380,COLORS.gray]].forEach(([k,e,x,c])=>{const obj=this.makeLabel(x,585,e+' 용기',125,c).setInteractive(new Phaser.Geom.Rectangle(-63,-28,126,56),Phaser.Geom.Rectangle.Contains);obj.setName('container_'+k);obj.on('pointerup',()=>{this.chosen.container=k;this.tweens.add({targets:obj,scale:1.08,yoyo:true,duration:130});audio.click();});});}
  makeServe(){this.serveButton=this.add.text(870,630,'SERVE',{fontFamily:'Arial',fontSize:'20px',fontStyle:'bold',color:'#ffffff',backgroundColor:'#ff7f6a',padding:{left:28,right:28,top:12,bottom:12}}).setOrigin(.5).setInteractive({useHandCursor:true});this.serveButton.on('pointerup',()=>this.serve());}
  serve(){const colorOk=this.chosen.color===this.order.color,decoOk=this.chosen.decos.includes(this.order.deco),containerOk=!this.order.container||this.chosen.container===this.order.container,mixOk=this.mixed;if(!(colorOk&&decoOk&&containerOk&&mixOk)){this.curious(this.customer);this.tweens.add({targets:this.orderIcons,scale:1.14,yoyo:true,repeat:1,duration:140});this.status.setText(!mixOk?'재료를 넣고 충분히 섞어야 해요':'주문 아이콘을 다시 확인해요. 만든 것은 그대로 유지돼요');this.registerFailure('serve_mismatch',this.orderBubble);return;}
    this.serveButton.disableInteractive();this.interactionLocked=true;telemetry('serve_success',{color:this.chosen.color,decos:this.chosen.decos,container:this.chosen.container});this.time.delayedCall(100,()=>this.tweens.add({targets:this.customer,scaleX:1.05,scaleY:1.05,duration:120}));this.time.delayedCall(220,()=>this.happy(this.customer));this.time.delayedCall(320,()=>audio.success());const coins=this.meta.round===1?3:this.meta.round===2?5:8;this.time.delayedCall(420,()=>this.coinBurst(coins));this.time.delayedCall(950,()=>{this.status.setText('완성품이 진열대에 놓였어요');});const creativity=Math.min(10,Math.max(0,this.chosen.decos.length-1)*5);this.time.delayedCall(1200,()=>{this.interactionLocked=false;this.finish({score:90+creativity});});}
  coinBurst(n){for(let i=0;i<n;i++){const c=this.add.text(650,420,'●',{fontSize:'22px',color:'#ffb703'}).setOrigin(.5).setDepth(5000);this.tweens.add({targets:c,x:930+(i%4)*28,y:345-(i%2)*30,duration:480,delay:i*35,ease:'Cubic.Out',onComplete:()=>c.destroy()});}audio.coin();this.coinCount+=n;if(this.coinCount>=5)this.unlockDecoration();}
  unlockDecoration(){const lock=this.add.text(950,570,'🔒',{fontSize:'28px'}).setOrigin(.5).setDepth(4000);this.tweens.add({targets:lock,angle:{from:-8,to:8},yoyo:true,repeat:2,duration:70,onComplete:()=>{lock.setText('✦');this.tweens.add({targets:lock,scale:{from:0,to:1.15},alpha:{from:0,to:1},duration:420,ease:'Back.Out',onComplete:()=>lock.destroy()});}});}
  debugState(){return {...super.debugState(),ingredients:[...this.ingredients],chosen:this.chosen,mixed:this.mixed,mixAngle:this.mixAngle,coinCount:this.coinCount};}
}
