const { test, expect } = require('@playwright/test');
const fs=require('fs');
const OFFICIAL='https://play-lh.googleusercontent.com/ZhT3SqfpofaxPlUUSlxPeUb0SbSVlfkA1LcubCNqdkXtb4FT4mZclYzFYC_7LW7eKA=w526-h296';
const NAILS=[[825,223],[845,194],[863,181],[884,188],[903,207]];
const BRUSH_CENTER=[820,515];
const BRUSH_PATHS=[
  [[765,485],[800,485],[755,500],[800,500],[755,485],[800,485],[755,500]],
  [[850,485],[895,485],[845,500],[895,500],[845,485],[895,485],[845,500]],
  [[765,535],[800,535],[755,555],[800,555],[755,535],[800,535],[755,555]],
  [[850,535],[895,535],[845,555],[895,555],[845,535],[895,535],[845,555]]
];
const PASTE_HOME=[980,490], BRUSH_PASTE_TARGET=[780,590], BRUSH_HOME=[1000,450], FACE_HOME=[640,260], CLIPPER_HOME=[985,250];
const FACE_LOOP=[[790,330],[735,330],[845,330],[735,345],[845,345],[735,315],[845,315],[790,330]];

async function p(page,x,y){return page.evaluate(({x,y})=>{const c=document.querySelector('canvas');const r=c.getBoundingClientRect();return{x:r.left+x/1280*r.width,y:r.top+y/720*r.height};},{x,y});}
async function beginDrag(page,pts,steps=2){const q=[];for(const a of pts)q.push(await p(page,a[0],a[1]));await page.mouse.move(q[0].x,q[0].y);await page.mouse.down();for(const a of q.slice(1))await page.mouse.move(a.x,a.y,{steps});}
async function drag(page,pts,steps=1){await beginDrag(page,pts,steps);await page.mouse.up();}
async function waitStep(page,n){await page.waitForFunction(step=>window.__ADUGAME_DEBUG__?.()?.step===step,n,{timeout:12000});}
async function snap(page,name){await page.waitForTimeout(90);await page.screenshot({path:`qa/reports/g1r2-fast/${name}.png`});}
async function debug(page,name){const d=await page.evaluate(()=>{
  const root=document.querySelector('#g1r2-v17-overlay');
  const vis=sel=>{const e=document.querySelector(sel);return e?{display:e.style.display,opacity:e.style.opacity,left:e.style.left,top:e.style.top,width:e.style.width,filter:e.style.filter,text:e.textContent,kind:e.dataset.kind}:null;};
  const box=sel=>{const e=document.querySelector(sel);if(!e)return null;const r=e.getBoundingClientRect(),rr=root?.getBoundingClientRect();return{font:parseFloat(getComputedStyle(e).fontSize),top:r.top,bottom:r.bottom,left:r.left,right:r.right,inside:!!rr&&r.left>=rr.left-1&&r.right<=rr.right+1&&r.top>=rr.top-1&&r.bottom<=rr.bottom+1,text:e.textContent};};
  const focus=[...root.querySelectorAll('div')].find(d=>d.style.borderWidth==='5px'&&d.style.position==='absolute'&&d.style.transform.includes('translate'));
  return {
    state:window.__ADUGAME_DEBUG__?.(),version:window.__ADUGAME_ART_SOURCE__?.G1R2?.version,generated:window.__ADUGAME_ART_SOURCE__?.G1R2?.generatedVisualAssets,
    ready:root?.dataset.ready,rootVersion:root?.dataset.version,uxReady:root?.dataset.uxReady,uxFeedback:root?.dataset.uxFeedback,nailRaiseReady:root?.dataset.nailRaiseReady,faceWashReady:root?.dataset.faceWashReady,bathroomBackdropReady:root?.dataset.bathroomBackdropReady,
    bathroomBackdrop:window.__ADUGAME_ART_SOURCE__?.G1R2?.bathroomBackdrop,dynamicUx:window.__ADUGAME_ART_SOURCE__?.G1R2?.dynamicUx,
    cursor:vis('.g1v17-ux-cursor'),pasteVisual:vis('.g1v17-paste'),brushVisual:vis('.g1v17-brush'),clothVisual:vis('.g1v17-cloth'),clipperVisual:vis('.g1v17-clipper'),washFeedbackOpacity:document.querySelector('.g1v17-wash-feedback')?.style.opacity,
    focus:focus?{left:focus.style.left,top:focus.style.top,width:focus.style.width,height:focus.style.height,opacity:focus.style.opacity}:null,
    brushGuides:[...document.querySelectorAll('.g1v17-ux-brush-zone')].map(e=>({done:e.dataset.done,left:e.style.left,top:e.style.top})),nailGuides:[...document.querySelectorAll('.g1v17-ux-nail-target')].map(e=>e.dataset.done),
    readability:{progress:box('.g1v17-ux-progress'),status:box('.g1v17-ux-status')},
    objects:(()=>{const s=window.__ADUGAME_SCENE__?.();return {paste:s?.paste?{x:s.paste.x,y:s.paste.y,home:s.paste.home}:null,brush:s?.brush?{x:s.brush.x,y:s.brush.y,home:s.brush.home}:null,cloth:s?.cloth?{x:s.cloth.x,y:s.cloth.y,home:s.cloth.home}:null,clipper:s?.clipper?{x:s.clipper.x,y:s.clipper.y,home:s.clipper.home}:null,mouth:s?.mouth?{x:s.mouth.x,y:s.mouth.y}:null,nails:(s?.nails||[]).map(n=>({x:n.x,y:n.y,i:n.nailIndex,active:n.active}))};})()
  };
});fs.writeFileSync(`qa/reports/g1r2-fast/${name}.json`,JSON.stringify(d,null,2));return d;}
async function ready(page){
  await page.goto('/index.html?game=1&round=2&e2e=1',{waitUntil:'domcontentloaded'});
  await page.waitForFunction(()=>{const r=document.querySelector('#g1r2-v17-overlay');return r?.dataset.ready==='1'&&r?.dataset.nailRaiseReady==='1'&&r?.dataset.faceWashReady==='1'&&r?.dataset.bathroomBackdropReady==='1'&&r?.dataset.uxReady==='1'&&r?.dataset.version==='17.25'&&window.__ADUGAME_ART_SOURCE__?.G1R2?.version==='v17.25';},null,{timeout:30000});
  await page.waitForTimeout(180);const d=await debug(page,'DEBUG-ready');expect(d.generated).toBe(0);expect(d.version).toBe('v17.25');expect(d.rootVersion).toBe('17.25');expect(d.uxReady).toBe('1');expect(d.nailRaiseReady).toBe('1');expect(d.faceWashReady).toBe('1');expect(d.bathroomBackdropReady).toBe('1');expect(d.bathroomBackdrop?.license).toContain('Public Domain');expect(d.dynamicUx?.pointerFeedbackFollowsInput).toBe(true);expect(d.dynamicUx?.standaloneDragArtHidden).toBe(true);expect(d.dynamicUx?.brushQuadrantFeedback).toBe(4);expect(d.dynamicUx?.nailTargetFeedback).toBe(5);expect(d.state?.benchmarkV5).toBe('brush-face-nails');expect(d.state?.g1r2V17Input).toBeTruthy();expect(Math.abs(d.objects.mouth.x-BRUSH_CENTER[0])).toBeLessThan(2);expect(Math.abs(d.objects.mouth.y-BRUSH_CENTER[1])).toBeLessThan(2);
  expect(d.readability.progress?.inside).toBe(true);expect(d.readability.status?.inside).toBe(true);expect(d.readability.progress?.font).toBeGreaterThanOrEqual(15);expect(d.readability.status?.font).toBeGreaterThanOrEqual(16);expect(d.readability.progress.bottom).toBeLessThanOrEqual(d.readability.status.top+4);return d;
}
async function brushQuadrant(page,index,evidence=false){const pts=BRUSH_PATHS[index];await beginDrag(page,[BRUSH_HOME,pts[0]],2);await page.waitForTimeout(70);if(evidence){const moving=await debug(page,'DEBUG-brush-dragging');expect(moving.state.g1r2V17Input.active).toBe('brush');expect(moving.cursor.display).toBe('flex');expect(moving.cursor.kind).toBe('brush');expect(moving.cursor.text).toBe('칫솔');expect(Math.abs(parseFloat(moving.cursor.left)-pts[0][0]/12.8)).toBeLessThan(1.2);expect(moving.brushVisual.display).toBe('none');await snap(page,'STEP-1b-brush-dragging');}
  for(const a of pts.slice(1)){const q=await p(page,a[0],a[1]);await page.mouse.move(q.x,q.y,{steps:1});}await page.mouse.up();await page.waitForTimeout(90);const d=await debug(page,`DEBUG-brush-q${index}`);expect(d.state.mouthProgress[index]).toBeGreaterThanOrEqual(115);expect(d.brushGuides[index].done).toBe('1');await page.waitForTimeout(150);}
async function washFaceWithDragEvidence(page){const start=await p(page,FACE_HOME[0],FACE_HOME[1]);const first=await p(page,735,330);await page.mouse.move(start.x,start.y);await page.mouse.down();await page.mouse.move(first.x,first.y,{steps:2});await page.waitForTimeout(70);const moving=await debug(page,'DEBUG-facewash-dragging');expect(moving.state.g1r2V17Input.active).toBe('cloth');expect(moving.cursor.display).toBe('flex');expect(moving.cursor.kind).toBe('cloth');expect(moving.cursor.text).toBe('세안');expect(Math.abs(parseFloat(moving.cursor.left)-735/12.8)).toBeLessThan(1.2);expect(moving.clothVisual.display).toBe('none');expect(Number(moving.washFeedbackOpacity)).toBeGreaterThan(.5);await snap(page,'STEP-2b-facewash-dragging');for(let i=0;i<4;i++){for(const [x,y] of FACE_LOOP){const q=await p(page,x,y);await page.mouse.move(q.x,q.y,{steps:1});}}await page.mouse.up();await waitStep(page,3);const done=await debug(page,'DEBUG-facewash-done');expect(done.state.faceWash).toBeGreaterThanOrEqual(360);return done;}
async function makeCompare(page,initial){const data=`data:image/png;base64,${initial.toString('base64')}`;await page.setViewportSize({width:1280,height:720});await page.setContent(`<!doctype html><style>*{box-sizing:border-box}body{margin:0;background:#121212;font-family:Arial;color:#fff;overflow:hidden}.w{width:1280px;height:720px;display:grid;grid-template-columns:1fr 1fr;gap:4px}.s{position:relative;display:flex;align-items:center;justify-content:center;background:#222;overflow:hidden;padding:12px}.l{position:absolute;left:12px;top:10px;background:#000c;border-radius:7px;padding:8px 11px;font-size:15px;font-weight:800;z-index:2}img{max-width:100%;max-height:100%;object-fit:contain}</style><div class=w><div class=s><div class=l>BABY PANDA · ACTION COMPOSITION</div><img id=o src="${OFFICIAL}"></div><div class=s><div class=l>ADUGAME · ACTUAL R2 v17.25</div><img src="${data}"></div></div>`,{waitUntil:'domcontentloaded'});await page.waitForFunction(()=>{const x=document.getElementById('o');return x?.complete&&x.naturalWidth>0},null,{timeout:12000});await page.screenshot({path:'qa/reports/g1r2-fast/COMPARE-v17.25.png'});}

test('R2 v17.25 aligned dynamic UX + real interaction evidence',async({page})=>{
  test.setTimeout(300000);fs.mkdirSync('qa/reports/g1r2-fast',{recursive:true});
  const start=await ready(page);expect(start.state.step).toBe(0);await snap(page,'STEP-0-toothpaste');const initial=await page.screenshot();
  await drag(page,[PASTE_HOME,[1080,500]]);await page.waitForTimeout(180);const miss=await debug(page,'DEBUG-toothpaste-miss');expect(miss.state.step).toBe(0);expect(miss.readability.progress.text).toContain('칫솔');await snap(page,'STEP-0a-toothpaste-miss-feedback');
  await page.waitForTimeout(260);await beginDrag(page,[PASTE_HOME,[900,535]],2);await page.waitForTimeout(70);const pasteMoving=await debug(page,'DEBUG-toothpaste-dragging');expect(pasteMoving.state.g1r2V17Input.active).toBe('paste');expect(pasteMoving.cursor.display).toBe('flex');expect(pasteMoving.cursor.kind).toBe('paste');expect(pasteMoving.cursor.text).toBe('치약');expect(Math.abs(parseFloat(pasteMoving.cursor.left)-900/12.8)).toBeLessThan(1.2);expect(pasteMoving.pasteVisual.display).toBe('none');await snap(page,'STEP-0b-toothpaste-dragging');const pasteTarget=await p(page,BRUSH_PASTE_TARGET[0],BRUSH_PASTE_TARGET[1]);await page.mouse.move(pasteTarget.x,pasteTarget.y,{steps:2});await page.mouse.up();await waitStep(page,1);await page.waitForTimeout(150);const brushReady=await debug(page,'DEBUG-brush-ready');expect(Math.abs(brushReady.objects.brush.x-BRUSH_HOME[0])).toBeLessThan(4);expect(Math.abs(brushReady.objects.brush.y-BRUSH_HOME[1])).toBeLessThan(4);expect(Math.abs(parseFloat(brushReady.focus.left)-BRUSH_CENTER[0]/12.8)).toBeLessThan(.5);expect(Math.abs(parseFloat(brushReady.focus.top)-BRUSH_CENTER[1]/7.2)).toBeLessThan(.5);expect(brushReady.readability.progress.text).toContain('양치');await snap(page,'STEP-1-brush');
  await brushQuadrant(page,0,true);await brushQuadrant(page,1);await brushQuadrant(page,2);await brushQuadrant(page,3);
  await waitStep(page,2);await page.waitForTimeout(150);const atFace=await debug(page,'DEBUG-facewash-ready');expect(Math.abs(atFace.objects.cloth.x-FACE_HOME[0])).toBeLessThan(4);expect(Math.abs(atFace.objects.cloth.y-FACE_HOME[1])).toBeLessThan(4);expect(Number(atFace.washFeedbackOpacity||0)).toBeLessThan(.1);expect(atFace.readability.progress.text).toContain('세수');await snap(page,'STEP-2-facewash');
  await washFaceWithDragEvidence(page);await page.waitForTimeout(120);const nailReady=await debug(page,'DEBUG-nails-ready');expect(Math.abs(nailReady.objects.clipper.x-CLIPPER_HOME[0])).toBeLessThan(4);expect(Math.abs(nailReady.objects.clipper.y-CLIPPER_HOME[1])).toBeLessThan(4);expect(nailReady.nailGuides).toEqual(['0','0','0','0','0']);await snap(page,'STEP-3-nails-focused');
  await beginDrag(page,[CLIPPER_HOME,[950,235],[925,215],NAILS[0]],2);await page.waitForTimeout(70);const clipping=await debug(page,'DEBUG-nail-clipping');expect(clipping.state.g1r2V17Input.active).toBe('clipper');expect(Number(clipping.clipperVisual.opacity)).toBeGreaterThan(.9);expect(Math.abs(parseFloat(clipping.clipperVisual.left)-NAILS[0][0]/12.8)).toBeLessThan(1.4);await snap(page,'STEP-3a-nail-clipping');await page.mouse.up();await page.waitForTimeout(100);let one=await debug(page,'DEBUG-nail-1');expect(one.state.clipped).toBe(1);expect(one.nailGuides[0]).toBe('1');expect(one.readability.progress.text).toContain('1/5');for(let i=1;i<NAILS.length;i++){await drag(page,[CLIPPER_HOME,[950,235],[925,215],NAILS[i]]);await page.waitForTimeout(90);const d=await debug(page,`DEBUG-nail-${i+1}`);expect(d.state.clipped).toBe(i+1);expect(d.nailGuides.slice(0,i+1).every(x=>x==='1')).toBe(true);if(i===2)await snap(page,'STEP-3b-nails-3of5');}
  await waitStep(page,4);await page.waitForTimeout(120);await snap(page,'STEP-4-done');const done=await debug(page,'DEBUG-done');expect(done.state.g1r2V17Input.pasteDown).toBeGreaterThanOrEqual(2);expect(done.state.g1r2V17Input.brushMove).toBeGreaterThan(0);expect(done.state.g1r2V17Input.clothMove).toBeGreaterThan(0);expect(done.state.g1r2V17Input.clipperUp).toBeGreaterThanOrEqual(5);expect(done.generated).toBe(0);expect(done.readability.progress.text).toContain('완료');await makeCompare(page,initial);
});
