const { test, expect } = require('@playwright/test');
const fs=require('fs');
const NAILS=[[825,223],[845,194],[863,181],[884,188],[903,207]];
const BRUSH_CENTER=[820,515];
const BRUSH_PATHS=[
  [[765,485],[800,485],[755,500],[800,500],[755,485],[800,485],[755,500]],
  [[850,485],[895,485],[845,500],[895,500],[845,485],[895,485],[845,500]],
  [[765,535],[800,535],[755,555],[800,555],[755,535],[800,535],[755,555]],
  [[850,535],[895,535],[845,555],[895,555],[845,535],[895,535],[845,555]]
];
const PASTE_HOME=[1155,500], BRUSH_PASTE_TARGET=[1015,645], BRUSH_HOME=[1080,505], FACE_HOME=[575,235], CLIPPER_HOME=[985,250];
const FACE_LOOP=[[790,330],[735,330],[845,330],[735,345],[845,345],[735,315],[845,315],[790,330]];

async function p(page,x,y){return page.evaluate(({x,y})=>{const c=document.querySelector('canvas');const r=c.getBoundingClientRect();return{x:r.left+x/1280*r.width,y:r.top+y/720*r.height};},{x,y});}
async function beginDrag(page,pts,steps=2){const q=[];for(const a of pts)q.push(await p(page,a[0],a[1]));await page.mouse.move(q[0].x,q[0].y);await page.mouse.down();for(const a of q.slice(1))await page.mouse.move(a.x,a.y,{steps});}
async function drag(page,pts,steps=1){await beginDrag(page,pts,steps);await page.mouse.up();}
async function waitStep(page,n){await page.waitForFunction(step=>window.__ADUGAME_DEBUG__?.()?.step===step,n,{timeout:12000});}
async function snap(page,name){await page.waitForTimeout(100);await page.screenshot({path:`qa/reports/g1r2-fast/${name}.png`});}
async function debug(page,name){const d=await page.evaluate(()=>{const root=document.querySelector('#g1r2-v17-overlay');const vis=sel=>{const e=document.querySelector(sel);return e?{display:e.style.display,opacity:e.style.opacity,left:e.style.left,top:e.style.top,text:e.textContent,kind:e.dataset.kind}:null;};const box=sel=>{const e=document.querySelector(sel);if(!e)return null;const r=e.getBoundingClientRect(),rr=root?.getBoundingClientRect();return{font:parseFloat(getComputedStyle(e).fontSize),top:r.top,bottom:r.bottom,left:r.left,right:r.right,inside:!!rr&&r.left>=rr.left-1&&r.right<=rr.right+1&&r.top>=rr.top-1&&r.bottom<=rr.bottom+1,text:e.textContent};};const focus=[...root.querySelectorAll('div')].find(d=>d.style.borderWidth==='5px'&&d.style.position==='absolute'&&d.style.transform.includes('translate'));return{state:window.__ADUGAME_DEBUG__?.(),version:window.__ADUGAME_ART_SOURCE__?.G1R2?.version,generated:window.__ADUGAME_ART_SOURCE__?.G1R2?.generatedVisualAssets,rootVersion:root?.dataset.version,finalReady:root?.dataset.toolHitAlignmentReady,finalFeedback:root?.dataset.finalUxFeedback,finalUx:window.__ADUGAME_ART_SOURCE__?.G1R2?.dynamicUxFinal,cursor:vis('.g1v17-ux-cursor'),washFeedbackOpacity:document.querySelector('.g1v17-wash-feedback')?.style.opacity,focus:focus?{left:focus.style.left,top:focus.style.top,width:focus.style.width,height:focus.style.height,opacity:focus.style.opacity}:null,brushGuides:[...document.querySelectorAll('.g1v17-ux-brush-zone')].map(e=>e.dataset.done),nailGuides:[...document.querySelectorAll('.g1v17-ux-nail-target')].map(e=>e.dataset.done),readability:{progress:box('.g1v17-ux-progress'),status:box('.g1v17-ux-status')},objects:(()=>{const s=window.__ADUGAME_SCENE__?.();return{paste:s?.paste?{x:s.paste.x,y:s.paste.y,home:s.paste.home}:null,brush:s?.brush?{x:s.brush.x,y:s.brush.y,home:s.brush.home}:null,cloth:s?.cloth?{x:s.cloth.x,y:s.cloth.y,home:s.cloth.home}:null,clipper:s?.clipper?{x:s.clipper.x,y:s.clipper.y,home:s.clipper.home}:null,mouth:s?.mouth?{x:s.mouth.x,y:s.mouth.y}:null};})()};});fs.writeFileSync(`qa/reports/g1r2-fast/${name}.json`,JSON.stringify(d,null,2));return d;}
async function ready(page){await page.goto('/index.html?game=1&round=2&e2e=1',{waitUntil:'domcontentloaded'});await page.waitForFunction(()=>{const r=document.querySelector('#g1r2-v17-overlay');return r?.dataset.ready==='1'&&r?.dataset.nailRaiseReady==='1'&&r?.dataset.faceWashReady==='1'&&r?.dataset.bathroomBackdropReady==='1'&&r?.dataset.uxReady==='1'&&r?.dataset.uxAlignmentReady==='1'&&r?.dataset.toolHitAlignmentReady==='1'&&r?.dataset.version==='17.27'&&window.__ADUGAME_ART_SOURCE__?.G1R2?.version==='v17.27';},null,{timeout:30000});await page.waitForTimeout(180);const d=await debug(page,'DEBUG-ready');expect(d.generated).toBe(0);expect(d.finalUx?.visibleToolHitAlignment).toBe(true);expect(d.finalUx?.pasteMissFeedback).toBe(true);expect(d.finalUx?.pointerPositionGuard).toBe(true);expect(Math.abs(d.objects.paste.x-PASTE_HOME[0])).toBeLessThan(3);expect(Math.abs(d.objects.paste.y-PASTE_HOME[1])).toBeLessThan(3);expect(Math.abs(d.objects.brush.x-BRUSH_PASTE_TARGET[0])).toBeLessThan(3);expect(Math.abs(d.objects.brush.y-BRUSH_PASTE_TARGET[1])).toBeLessThan(3);expect(Math.abs(d.objects.mouth.x-BRUSH_CENTER[0])).toBeLessThan(2);expect(Math.abs(d.objects.mouth.y-BRUSH_CENTER[1])).toBeLessThan(2);expect(Math.abs(parseFloat(d.focus.left)-PASTE_HOME[0]/12.8)).toBeLessThan(.7);expect(Math.abs(parseFloat(d.focus.top)-PASTE_HOME[1]/7.2)).toBeLessThan(.7);expect(d.readability.progress?.inside).toBe(true);expect(d.readability.status?.inside).toBe(true);expect(d.readability.progress.font).toBeGreaterThanOrEqual(15);expect(d.readability.status.font).toBeGreaterThanOrEqual(16);return d;}
async function brushQuadrant(page,index,evidence=false){const pts=BRUSH_PATHS[index];await beginDrag(page,[BRUSH_HOME,pts[0]],2);await page.waitForTimeout(80);if(evidence){const moving=await debug(page,'DEBUG-brush-dragging');expect(moving.state.g1r2V17Input.active).toBe('brush');expect(moving.cursor.display).toBe('flex');expect(moving.cursor.kind).toBe('brush');expect(Math.abs(parseFloat(moving.cursor.left)-pts[0][0]/12.8)).toBeLessThan(1.2);await snap(page,'STEP-1b-brush-dragging');}for(const a of pts.slice(1)){const q=await p(page,a[0],a[1]);await page.mouse.move(q.x,q.y,{steps:1});}await page.mouse.up();await page.waitForTimeout(100);const d=await debug(page,`DEBUG-brush-q${index}`);expect(d.state.mouthProgress[index]).toBeGreaterThanOrEqual(115);expect(d.brushGuides[index]).toBe('1');}
async function washFace(page){const start=await p(page,FACE_HOME[0],FACE_HOME[1]);const first=await p(page,735,330);await page.mouse.move(start.x,start.y);await page.mouse.down();await page.mouse.move(first.x,first.y,{steps:2});await page.waitForTimeout(80);const moving=await debug(page,'DEBUG-facewash-dragging');expect(moving.state.g1r2V17Input.active).toBe('cloth');expect(moving.cursor.display).toBe('flex');expect(moving.cursor.kind).toBe('cloth');expect(Number(moving.washFeedbackOpacity)).toBeGreaterThan(.5);await snap(page,'STEP-2b-facewash-dragging');for(let i=0;i<4;i++){for(const [x,y] of FACE_LOOP){const q=await p(page,x,y);await page.mouse.move(q.x,q.y,{steps:1});}}await page.mouse.up();await waitStep(page,3);}

test('R2 v17.27 final dynamic UX visual-hit alignment',async({page})=>{test.setTimeout(300000);fs.mkdirSync('qa/reports/g1r2-fast',{recursive:true});const start=await ready(page);expect(start.state.step).toBe(0);await snap(page,'STEP-0-toothpaste');
  await drag(page,[PASTE_HOME,[900,500]]);await page.waitForTimeout(180);const miss=await debug(page,'DEBUG-toothpaste-miss');expect(miss.state.step).toBe(0);expect(miss.finalFeedback).toBe('paste-miss');expect(miss.readability.progress.text).toContain('여기가 아니에요');await snap(page,'STEP-0a-toothpaste-miss-feedback');
  await beginDrag(page,[PASTE_HOME,[1110,560]],2);await page.waitForTimeout(80);const pasteMoving=await debug(page,'DEBUG-toothpaste-dragging');expect(pasteMoving.state.g1r2V17Input.active).toBe('paste');expect(pasteMoving.cursor.display).toBe('flex');expect(pasteMoving.cursor.kind).toBe('paste');expect(Math.abs(parseFloat(pasteMoving.cursor.left)-1110/12.8)).toBeLessThan(1.2);await snap(page,'STEP-0b-toothpaste-dragging');const tgt=await p(page,BRUSH_PASTE_TARGET[0],BRUSH_PASTE_TARGET[1]);await page.mouse.move(tgt.x,tgt.y,{steps:3});await page.mouse.up();await waitStep(page,1);await page.waitForTimeout(150);
  const b=await debug(page,'DEBUG-brush-ready');expect(Math.abs(b.objects.brush.x-BRUSH_HOME[0])).toBeLessThan(3);expect(Math.abs(b.objects.brush.y-BRUSH_HOME[1])).toBeLessThan(3);expect(Math.abs(parseFloat(b.focus.left)-BRUSH_CENTER[0]/12.8)).toBeLessThan(.6);expect(Math.abs(parseFloat(b.focus.top)-BRUSH_CENTER[1]/7.2)).toBeLessThan(.6);await snap(page,'STEP-1-brush');
  await brushQuadrant(page,0,true);await brushQuadrant(page,1);await brushQuadrant(page,2);await brushQuadrant(page,3);await waitStep(page,2);await page.waitForTimeout(150);
  const f=await debug(page,'DEBUG-facewash-ready');expect(Math.abs(f.objects.cloth.x-FACE_HOME[0])).toBeLessThan(3);expect(Math.abs(f.objects.cloth.y-FACE_HOME[1])).toBeLessThan(3);await snap(page,'STEP-2-facewash');await washFace(page);await page.waitForTimeout(120);
  const n=await debug(page,'DEBUG-nails-ready');expect(Math.abs(n.objects.clipper.x-CLIPPER_HOME[0])).toBeLessThan(4);expect(Math.abs(n.objects.clipper.y-CLIPPER_HOME[1])).toBeLessThan(4);expect(n.nailGuides).toEqual(['0','0','0','0','0']);await snap(page,'STEP-3-nails-focused');
  for(let i=0;i<NAILS.length;i++){if(i===0){await beginDrag(page,[CLIPPER_HOME,[950,235],NAILS[i]],2);await page.waitForTimeout(80);await snap(page,'STEP-3a-nail-clipping');await page.mouse.up();}else await drag(page,[CLIPPER_HOME,[950,235],NAILS[i]]);await page.waitForTimeout(100);const d=await debug(page,`DEBUG-nail-${i+1}`);expect(d.state.clipped).toBe(i+1);expect(d.nailGuides.slice(0,i+1).every(x=>x==='1')).toBe(true);if(i===2)await snap(page,'STEP-3b-nails-3of5');}
  await waitStep(page,4);await page.waitForTimeout(120);await snap(page,'STEP-4-done');const done=await debug(page,'DEBUG-done');expect(done.state.g1r2V17Input.pasteDown).toBeGreaterThanOrEqual(2);expect(done.state.g1r2V17Input.brushMove).toBeGreaterThan(0);expect(done.state.g1r2V17Input.clothMove).toBeGreaterThan(0);expect(done.state.g1r2V17Input.clipperUp).toBeGreaterThanOrEqual(5);expect(done.generated).toBe(0);
});
