const { test } = require('@playwright/test');
const OFFICIAL='https://play-lh.googleusercontent.com/ZhT3SqfpofaxPlUUSlxPeUb0SbSVlfkA1LcubCNqdkXtb4FT4mZclYzFYC_7LW7eKA=w526-h296';
const CANDIDATES=[
 ['wash-boy','https://openclipart.org/image/2000px/312394','oksmith · publicdomainq/Openclipart public domain'],
 ['siblings','https://publicdomainq.net/images/202007/24s/publicdomainq-0047297fns.jpg','PublicDomainQ · CC0 public domain'],
 ['pdq-boy-thumb','https://publicdomainq.net/images/202001/27s/publicdomainq-0042284ufa.jpg','PublicDomainQ · CC0 public domain']
];
test('G1R2 final child handwashing scenes',async({page})=>{
 test.setTimeout(90000);await page.setViewportSize({width:1280,height:720});require('fs').mkdirSync('qa/reports/g1r2-fast',{recursive:true});
 for(let i=0;i<CANDIDATES.length;i++){const[id,url,credit]=CANDIDATES[i];await page.setContent(`<!doctype html><style>*{box-sizing:border-box}body{margin:0;background:#151515;font-family:Arial;color:white}.w{width:1280px;height:720px;display:grid;grid-template-columns:1fr 1fr;gap:4px}.s{position:relative;display:flex;align-items:center;justify-content:center;overflow:hidden;padding:18px;background:#222}.c{background:#f4fbff}.l,.cr{position:absolute;z-index:2;background:#000b;border-radius:6px;padding:7px 10px}.l{left:12px;top:10px;font-weight:700}.cr{right:12px;bottom:10px;font-size:12px}img{max-width:100%;max-height:100%;object-fit:contain}</style><div class=w><div class=s><div class=l>BABY PANDA · ACTION COMPOSITION</div><img id=o src="${OFFICIAL}"></div><div class="s c"><div class=l>${id.toUpperCase()}</div><img id=c src="${url}"><div class=cr>${credit}</div></div></div>`,{waitUntil:'domcontentloaded'});const ok=await page.evaluate(()=>Promise.all(['o','c'].map(id=>new Promise(r=>{const x=document.getElementById(id);if(x.complete)return r(x.naturalWidth>0);const t=setTimeout(()=>r(false),10000);x.onload=()=>{clearTimeout(t);r(true)};x.onerror=()=>{clearTimeout(t);r(false)}}))));console.log(id,ok);await page.waitForTimeout(250);await page.screenshot({path:`qa/reports/g1r2-fast/CHILD-${i+1}-${id}.png`});}
});